export const GUARDIAN_SET_DATA = 'GUARDIAN_SET_DATA';
export const GUARDIAN_SET_ACCESORY = 'GUARDIAN_SET_ACCESORY';
export const GUARDIAN_RESET = 'GUARDIAN_RESET';
export const GUARDIAN_SET_AVAILABLE_PLANS = 'GUARDIAN_SET_AVAILABLE_PLANS';
export const GUARDIAN_SET_GUEARDIAN_STUDENT_PLAN = 'GUARDIAN_SET_GUEARDIAN_STUDENT_PLAN'
export const GUARDIAN_SET_STUDENT = 'GUARDIAN_SET_STUDENT'
export const GUARDIAN_UPDATE_EMAIL_PWD = 'GUARDIAN_UPDATE_EMAIL_PWD'
export const GUARDIAN_PAYMENT_METHOD_INFO = 'GUARDIAN_PAYMENT_METHOD_INFO'


