export const USER_SET_DATA = 'USER_SET_DATA';
export const USER_RESET = 'USER_SET_RESET';
export const USER_SET_LANGUAGE = 'USER_SET_LANGUAGE';
export const USER_SET_TOGGLE_SOUND = 'USER_SET_TOGGLE_SOUND';
export const USER_SET_REWARDFUL_ID = 'USER_SET_REWARDFUL_ID';
